/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gal.tools.cvs.gui;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;
import javax.swing.JTree;

/**
 *
 * @author oem
 */
public class CVSHistoryWindow extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form CVSHistoryWindow
     */
    public CVSHistoryWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpView = new javax.swing.ButtonGroup();
        toolbar = new javax.swing.JToolBar();
        btnShowCurrentWS = new javax.swing.JToggleButton();
        btnShowAsList = new javax.swing.JToggleButton();
        separator1 = new javax.swing.JToolBar.Separator();
        btnExpandAll = new javax.swing.JButton();
        btnCollapseAll = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnWDCModelView = new javax.swing.JToggleButton();
        btnJiraModelView = new javax.swing.JToggleButton();
        
        btnDWCModel = new javax.swing.JToggleButton();
        btnResourcesModel = new javax.swing.JToggleButton();
        btnDirectoryModel = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        pnContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        toolbarSearch = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        chbRegexp = new javax.swing.JCheckBox();
        lblFrom = new javax.swing.JLabel();
        spShowFrom = new javax.swing.JSpinner();
        lblTo = new javax.swing.JLabel();
        spShowTo = new javax.swing.JSpinner();
        chbUseDateRange = new javax.swing.JCheckBox();
        lbNumbuerRows = new javax.swing.JLabel();
        spLimit = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CVS commit history");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 2147483647));
        setPreferredSize(new java.awt.Dimension(450, 600));

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        btnShowCurrentWS.setText("Current WS");
        btnShowCurrentWS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowCurrentWS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnShowCurrentWS);

        btnShowAsList.setText("Show resources as list");
        btnShowAsList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowAsList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnShowAsList);
        toolbar.add(separator1);

        btnExpandAll.setText("Expand all");
        btnExpandAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExpandAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnExpandAll);

        btnCollapseAll.setText("Collapse all");
        btnCollapseAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCollapseAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnCollapseAll);
        toolbar.add(jSeparator1);

        btnGrpView.add(btnWDCModelView);
        btnWDCModelView.setSelected(true);
        btnWDCModelView.setText("Show by workspace");
        btnWDCModelView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWDCModelView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnWDCModelView);

        
        btnGrpView.add(btnJiraModelView);
        btnJiraModelView.setText("Show only JIRA Issues");
        btnJiraModelView.setFocusable(false);
        btnJiraModelView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJiraModelView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnJiraModelView);
        
        btnGrpView.add(btnDWCModel);
        btnDWCModel.setText("Show by date");
        btnDWCModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDWCModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnDWCModel);

        btnGrpView.add(btnResourcesModel);
        btnResourcesModel.setText("Show by files");
        btnResourcesModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResourcesModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnResourcesModel);

        btnGrpView.add(btnDirectoryModel);
        btnDirectoryModel.setText("Show by projects");
        btnDirectoryModel.setFocusable(false);
        btnDirectoryModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDirectoryModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(btnDirectoryModel);
        toolbar.add(jSeparator2);

        getContentPane().add(toolbar, java.awt.BorderLayout.PAGE_START);

        pnContent.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(tree);

        pnContent.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        toolbarSearch.setFloatable(false);
        toolbarSearch.setRollover(true);

        jLabel1.setText(" Search ");
        toolbarSearch.add(jLabel1);

        search.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        toolbarSearch.add(search);

        chbRegexp.setText("Regexp");
        chbRegexp.setFocusable(false);
        chbRegexp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chbRegexp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        
        toolbarSearch.add(chbRegexp);

        lblFrom.setText("  From ");
        toolbarSearch.add(lblFrom);

        spShowFrom.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        spShowFrom.setEditor(new javax.swing.JSpinner.DateEditor(spShowFrom, "dd/MM/yyyy"));
        spShowFrom.setMaximumSize(new java.awt.Dimension(80, 32767));
        toolbarSearch.add(spShowFrom);

        lblTo.setText(" To ");
        toolbarSearch.add(lblTo);

        spShowTo.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        spShowTo.setEditor(new javax.swing.JSpinner.DateEditor(spShowTo, "dd/MM/yyyy"));
        spShowTo.setMaximumSize(new java.awt.Dimension(80, 32767));
        toolbarSearch.add(spShowTo);

        chbUseDateRange.setToolTipText("Use date range");
        chbUseDateRange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chbUseDateRange.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarSearch.add(chbUseDateRange);

        lbNumbuerRows.setText(" Limit ");
        toolbarSearch.add(lbNumbuerRows);

        spLimit.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spLimit.setEditor(new javax.swing.JSpinner.NumberEditor(spLimit, "#"));
        spLimit.setMaximumSize(new java.awt.Dimension(50, 32767));
        toolbarSearch.add(spLimit);
        toolbarSearch.add(jSeparator4);

        btnRefresh.setText("Refresh");
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbarSearch.add(btnRefresh);

        pnContent.add(toolbarSearch, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCollapseAll() {
        return btnCollapseAll;
    }

    public JButton getBtnExpandAll() {
        return btnExpandAll;
    }

    public JToggleButton getBtnShowAsList() {
        return btnShowAsList;
    }

    public JToggleButton getBtnShowCurrentWS() {
        return btnShowCurrentWS;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }


    public JPanel getPnContent() {
        return pnContent;
    }

    public JTextField getSearch() {
        return search;
    }

    public JToolBar.Separator getSeparator1() {
        return separator1;
    }


    public JToolBar getToolbar() {
        return toolbar;
    }

    /**
     * @param args the command line arguments
     */
    public JTree getTree() {
        return tree;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CVSHistoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CVSHistoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CVSHistoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CVSHistoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CVSHistoryWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollapseAll;
    private javax.swing.JToggleButton btnDWCModel;
    private javax.swing.JToggleButton btnDirectoryModel;
    private javax.swing.JButton btnExpandAll;
    private javax.swing.ButtonGroup btnGrpView;
    private javax.swing.JToggleButton btnJiraModelView;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JToggleButton btnResourcesModel;
    private javax.swing.JToggleButton btnShowAsList;
    private javax.swing.JToggleButton btnShowCurrentWS;
    
    private javax.swing.JToggleButton btnWDCModelView;
    private javax.swing.JCheckBox chbRegexp;
    private javax.swing.JCheckBox chbUseDateRange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JLabel lbNumbuerRows;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel pnContent;
    private javax.swing.JTextField search;
    private javax.swing.JToolBar.Separator separator1;
    private javax.swing.JSpinner spLimit;
    private javax.swing.JSpinner spShowFrom;
    private javax.swing.JSpinner spShowTo;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JToolBar toolbarSearch;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getBtnDWCModel() {
        return btnDWCModel;
    }

    public ButtonGroup getBtnGrpView() {
        return btnGrpView;
    }

    public JToggleButton getBtnWDCModelView() {
        return btnWDCModelView;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public JToggleButton getBtnResourcesModel() {
        return btnResourcesModel;
    }

    public JSpinner getSpLimit() {
        return spLimit;
    }

    public JSpinner getSpShowFrom() {
        return spShowFrom;
    }

    public JSpinner getSpShowTo() {
        return spShowTo;
    }

    public JToggleButton getBtnDirectoryModel() {
        return btnDirectoryModel;
    }

    public JToggleButton getBtnJiraModelView() {
        return btnJiraModelView;
    }

	public javax.swing.JLabel getLbNumbuerRows() {
		return lbNumbuerRows;
	}

	public javax.swing.JLabel getLblFrom() {
		return lblFrom;
	}

	public javax.swing.JLabel getLblTo() {
		return lblTo;
	}

	public javax.swing.JCheckBox getChbRegexp() {
		return chbRegexp;
	}

	public javax.swing.JCheckBox getChbUseDateRange() {
		return chbUseDateRange;
	}
	
}
